FROM tensorflow/serving:latest

RUN mkdir -p /home/uuihome/uui

WORKDIR /home/uuihome/uui

RUN groupadd uui -g 1000

RUN useradd -u 1000 -d /home/uuihome/uui -g uui -s /bin/bash uui

RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install wget -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install unzip -y

RUN DEBIAN_FRONTEND=noninteractive apt-get install python3-pip python3-dev build-essential -y
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN ln -s /usr/bin/pip3 /usr/bin/pip

COPY requirements /home/uuihome/uui/requirements
RUN DEBIAN_FRONTEND=noninteractive pip install -r requirements
COPY scripts /home/uuihome/uui/scripts
COPY run.sh /home/uuihome/uui/run.sh

RUN chown -R uui:uui /home/uuihome/uui
USER uui
ENTRYPOINT /home/uuihome/uui/run.sh